import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { getCategories, generateQuizAI } from "../../services/quiz.service";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../../components/ui/select";
import {
  BrainCircuit,
  Cpu,
  Sparkles,
  ArrowRight,
  Clock,
  BookOpen,
  CheckCircle2,
  ListCollapse,
  Loader2,
  Award,
  BookMarked,
  LayoutDashboard
} from "lucide-react";
import { toast } from "react-hot-toast";

const LOADING_STEPS = [
  "Initializing Quizify AI intelligence core...",
  "Retrieving topic data and structuring curriculum...",
  "Drafting adaptive multiple choice questions...",
  "Calibrating question difficulties and cognitive loads...",
  "Compiling comprehensive answer explanations...",
  "Validating and committing quiz database entries...",
];

export default function GenerateQuizPage() {
  const navigate = useNavigate();
  const [categories, setCategories] = useState([]);
  const [isLoadingCategories, setIsLoadingCategories] = useState(false);
  
  // Form state
  const [formData, setFormData] = useState({
    topic: "",
    categoryId: "",
    difficulty: "medium",
    numQuestions: 5,
  });

  // AI loading state
  const [isGenerating, setIsGenerating] = useState(false);
  const [currentStepIdx, setCurrentStepIdx] = useState(0);

  // Result state
  const [generatedResult, setGeneratedResult] = useState(null);

  // Fetch categories on mount
  useEffect(() => {
    const fetchCategories = async () => {
      setIsLoadingCategories(true);
      try {
        const res = await getCategories();
        if (res && res.data) {
          setCategories(res.data);
          if (res.data.length > 0) {
            setFormData(prev => ({ ...prev, categoryId: res.data[0]._id }));
          }
        }
      } catch (err) {
        console.error("Failed to load categories:", err);
        toast.error("Failed to load categories");
      } finally {
        setIsLoadingCategories(false);
      }
    };
    fetchCategories();
  }, []);

  // Cycle loading status text
  useEffect(() => {
    let interval;
    if (isGenerating) {
      interval = setInterval(() => {
        setCurrentStepIdx(prev => {
          if (prev < LOADING_STEPS.length - 1) {
            return prev + 1;
          }
          return prev; // hold on last step until API resolves
        });
      }, 3000);
    } else {
      setCurrentStepIdx(0);
    }
    return () => clearInterval(interval);
  }, [isGenerating]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleGenerateSubmit = async (e) => {
    e.preventDefault();
    if (!formData.topic.trim()) {
      return toast.error("Please enter a quiz topic");
    }
    if (!formData.categoryId) {
      return toast.error("Please select a category");
    }

    setIsGenerating(true);
    setGeneratedResult(null);

    try {
      const res = await generateQuizAI({
        topic: formData.topic,
        categoryId: formData.categoryId,
        difficulty: formData.difficulty,
        numQuestions: Number(formData.numQuestions),
      });

      if (res && res.status === "success") {
        setGeneratedResult(res.data);
        toast.success("Quiz successfully generated by AI!");
      } else {
        toast.error("Failed to generate quiz");
      }
    } catch (err) {
      console.error(err);
      toast.error(err.response?.data?.message || "AI generation failed");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-fadeIn">
      {/* Title */}
      <div>
        <h1 className="text-2xl font-bold tracking-tight">AI Quiz Generator</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Harness the power of AI to instantly craft adaptive, high-quality quizzes on any subject.
        </p>
      </div>

      <Separator className="bg-border/60" />

      {isGenerating ? (
        /* PREMIUM LOADING WORKFLOW STATE */
        <Card className="border border-indigo-500/20 bg-indigo-500/5 backdrop-blur-md p-8 md:p-12 text-center flex flex-col items-center justify-center space-y-6 min-h-[400px]">
          <div className="relative">
            <div className="absolute inset-0 bg-indigo-500/20 rounded-full blur-xl animate-pulse"></div>
            <div className="w-16 h-16 rounded-full bg-gradient-to-tr from-indigo-500 to-violet-600 flex items-center justify-center text-white shadow-lg animate-spin duration-3000 relative">
              <Cpu size={30} className="animate-pulse" />
            </div>
          </div>

          <div className="space-y-2 max-w-md">
            <h3 className="text-lg font-bold text-foreground flex items-center justify-center gap-2">
              Generating Quiz <Sparkles size={16} className="text-indigo-500 animate-bounce" />
            </h3>
            <p className="text-xs text-indigo-600 dark:text-indigo-400 font-semibold uppercase tracking-wider animate-pulse min-h-[16px]">
              {LOADING_STEPS[currentStepIdx]}
            </p>
            <p className="text-[11px] text-muted-foreground leading-relaxed pt-2">
              This process may take 15 to 30 seconds as our LLM builds, validates, and tags high-quality questions for your curriculum.
            </p>
          </div>

          <div className="w-48 bg-muted rounded-full h-1.5 overflow-hidden">
            <div 
              className="bg-indigo-600 h-1.5 rounded-full transition-all duration-1000"
              style={{ width: `${((currentStepIdx + 1) / LOADING_STEPS.length) * 100}%` }}
            ></div>
          </div>
        </Card>
      ) : generatedResult ? (
        /* AI GENERATED RESULT VIEW */
        <div className="space-y-6">
          {/* Success summary card */}
          <Card className="border border-emerald-500/20 bg-emerald-500/5 backdrop-blur-xs">
            <CardHeader className="pb-4">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-emerald-600 text-white rounded-xl shadow-md">
                  <CheckCircle2 size={22} />
                </div>
                <div>
                  <CardTitle className="text-base font-bold text-foreground">Generation Complete!</CardTitle>
                  <CardDescription className="text-xs">Your AI quiz is fully parsed and compiled in the database.</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="p-4 rounded-xl border border-border/80 bg-card flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div>
                  <h4 className="text-sm font-bold text-foreground">{generatedResult.quiz?.title}</h4>
                  <p className="text-xs text-muted-foreground mt-0.5">{generatedResult.quiz?.description}</p>
                </div>
                <div className="flex items-center gap-3 shrink-0">
                  <Badge variant="secondary" className="capitalize text-[10px] font-bold py-0.5">
                    {generatedResult.quiz?.difficulty}
                  </Badge>
                  <span className="text-[10px] text-muted-foreground">
                    {generatedResult.questions?.length || 0} Questions
                  </span>
                </div>
              </div>
            </CardContent>
            <CardFooter className="flex justify-between items-center border-t border-border/30 px-6 py-4 bg-muted/10 rounded-b-lg">
              <Button
                variant="outline"
                size="sm"
                className="text-xs gap-1.5 cursor-pointer"
                onClick={() => navigate("/dashboard")}
              >
                <LayoutDashboard size={13} /> Dashboard
              </Button>
              <Button
                size="sm"
                className="text-xs bg-indigo-600 hover:bg-indigo-700 text-white gap-1.5 cursor-pointer shadow-md shadow-indigo-600/10"
                onClick={() => setGeneratedResult(null)}
              >
                <BrainCircuit size={13} /> Generate Another
              </Button>
            </CardFooter>
          </Card>

          {/* List of generated questions */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground px-1 flex items-center gap-1.5">
              <BookMarked size={12} className="text-indigo-500" /> Generated Quiz Questions
            </h4>
            
            <div className="space-y-3">
              {generatedResult.questions?.map((q, qIdx) => (
                <Card key={q._id || qIdx} className="border border-border/80 bg-card/40">
                  <CardHeader className="p-4 pb-2">
                    <div className="flex gap-2 items-start">
                      <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400 mt-0.5">{qIdx + 1}.</span>
                      <h4 className="text-xs font-bold text-foreground leading-relaxed">{q.text}</h4>
                    </div>
                  </CardHeader>
                  <CardContent className="px-8 pb-4 space-y-3">
                    <div className="grid gap-2 sm:grid-cols-2">
                      {q.options?.map((option, oIdx) => {
                        const isCorrect = q.correctAnswer?.includes(oIdx);
                        return (
                          <div
                            key={oIdx}
                            className={`p-2.5 rounded-lg border text-xs font-medium flex items-center gap-2 ${
                              isCorrect
                                ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-700 dark:text-emerald-400"
                                : "bg-muted/30 border-border/60 text-muted-foreground"
                            }`}
                          >
                            <span className="text-[10px] font-bold opacity-60">
                              {String.fromCharCode(65 + oIdx)})
                            </span>
                            <span>{option}</span>
                          </div>
                        );
                      })}
                    </div>
                    {q.explanation && (
                      <div className="p-3 rounded-lg bg-indigo-500/5 border border-indigo-500/10 text-[11px] text-muted-foreground leading-relaxed">
                        <span className="font-bold text-indigo-600 dark:text-indigo-400 mr-1.5">Explanation:</span>
                        {q.explanation}
                      </div>
                    )}
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </div>
      ) : (
        /* INPUT FORM STATE */
        <div className="grid gap-6 md:grid-cols-3">
          <div className="md:col-span-1 space-y-2">
            <h3 className="text-sm font-semibold">AI Settings</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Define the subject matter, target audience difficulty, and quantity of questions for the generator.
            </p>
          </div>

          <Card className="md:col-span-2 border border-border/80 bg-card/40 backdrop-blur-md">
            <form onSubmit={handleGenerateSubmit}>
              <CardHeader>
                <CardTitle className="text-base font-semibold">Prompt Generator Configuration</CardTitle>
                <CardDescription className="text-xs">Describe the topic below to feed the AI prompt compiler.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-5">
                <div className="space-y-2">
                  <Label htmlFor="topic" className="text-xs font-semibold">Quiz Topic</Label>
                  <Input
                    id="topic"
                    name="topic"
                    placeholder="e.g. React hooks, French Revolution, Quantum Computing basics"
                    value={formData.topic}
                    onChange={handleInputChange}
                    required
                  />
                  <p className="text-[10px] text-muted-foreground/80">
                    Be specific for better questions (e.g. "React useEffect cleanups" instead of just "React").
                  </p>
                </div>

                <div className="grid gap-4 sm:grid-cols-3">
                  <div className="space-y-2">
                    <Label htmlFor="categoryId" className="text-xs font-semibold">Target Category</Label>
                    <Select
                      value={formData.categoryId}
                      onValueChange={(val) => setFormData(prev => ({ ...prev, categoryId: val }))}
                    >
                      <SelectTrigger className="w-full h-8 bg-card dark:bg-input/20">
                        <SelectValue placeholder={isLoadingCategories ? "Loading..." : "Select Category"} />
                      </SelectTrigger>
                      <SelectContent>
                        {categories.length === 0 ? (
                          <SelectItem value="none" disabled>No categories</SelectItem>
                        ) : (
                          categories.map(c => (
                            <SelectItem key={c._id} value={c._id}>{c.name}</SelectItem>
                          ))
                        )}
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="difficulty" className="text-xs font-semibold">Difficulty Calibration</Label>
                    <Select
                      value={formData.difficulty}
                      onValueChange={(val) => setFormData(prev => ({ ...prev, difficulty: val }))}
                    >
                      <SelectTrigger className="w-full h-8 bg-card dark:bg-input/20">
                        <SelectValue placeholder="Select Difficulty" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="easy">Easy</SelectItem>
                        <SelectItem value="medium">Medium</SelectItem>
                        <SelectItem value="hard">Hard</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="numQuestions" className="text-xs font-semibold">Question Quantity</Label>
                    <Select
                      value={String(formData.numQuestions)}
                      onValueChange={(val) => setFormData(prev => ({ ...prev, numQuestions: Number(val) }))}
                    >
                      <SelectTrigger className="w-full h-8 bg-card dark:bg-input/20">
                        <SelectValue placeholder="Select Quantity" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="3">3 Questions (Quick)</SelectItem>
                        <SelectItem value="5">5 Questions (Standard)</SelectItem>
                        <SelectItem value="10">10 Questions (Complete)</SelectItem>
                        <SelectItem value="15">15 Questions (Challenge)</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </CardContent>
              <CardFooter className="flex justify-between items-center border-t border-border/40 bg-muted/20 px-6 py-4 rounded-b-lg">
                <Button variant="ghost" type="button" onClick={() => navigate("/dashboard")} className="text-xs">
                  Cancel
                </Button>
                <Button type="submit" className="text-xs bg-indigo-600 hover:bg-indigo-700 text-white gap-2 cursor-pointer shadow-md shadow-indigo-600/10">
                  <Sparkles size={14} className="text-amber-400 fill-amber-400 animate-pulse" /> Generate Quiz with AI
                </Button>
              </CardFooter>
            </form>
          </Card>
        </div>
      )}
    </div>
  );
}
